name: mermaid-dev  # Replace with your desired environment name
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pandas
  - numpy
  - duckdb
  - pyarrow
  - boto3
  - botocore
  - s3transfer
  - s3fs
  - scikit-learn
  - pip
  - pip:
    - python-dotenv
    - pyspacer==0.9.0


